export default function Head() {
    return (
        <>
            <title>Locus</title>
            <meta
                content="width=device-width, initial-scale=1"
                name="viewport"
            />
            <meta
                name="An app for location Roman sites in Scotland"
                content="Generated by create next app"
            />
            <link rel="icon" href="/favicon.ico" />
        </>
    )
}
